# Spring LDAP Mapping Attributes to POJO with AttributesMapper configuration application.yml

spring:
  ldap:

    # Spring LDAP
    #
    # In this example we use an embedded ldap server. When using a real one,
    # you can configure the settings here.
    #
    # urls: ldap://localhost:12345
    # base: dc=example,dc=com
    # username: uid=admin
    # password: secret

    # Embedded Spring LDAP
    embedded:
      base-dn: dc=example,dc=com
      credential:
        username: cn=admin
        password: secret
      ldif: classpath:schema.ldif
      url: ldap://localhost:8389/
      port: 8389
      validation:
        enabled: false
